import = ["/home/chu/.config/alacritty/alacritty-theme/themes/github_dark.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Home"
mode = "AppCursor"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Home"
mode = "~AppCursor"

[window]
opacity = 1.0

[window.padding]
x = 2
y = 0
